/**
 * This method auto adds to the list of actions the suffixes
 * provided by `redux-promise-middleware`.
 *
 * Example:
 *
 * const actionTypes = createActionsTypes(['GET_USER', 'CREATE_USER'])
 *
 * [object Object] {
 *   CREATE_USER: "CREATE_USER",
 *   CREATE_USER_FULFILLED: "CREATE_USER_FULFILLED",
 *   CREATE_USER_PENDING: "CREATE_USER_PENDING",
 *   CREATE_USER_REJECTED: "CREATE_USER_REJECTED",
 *
 *   GET_USER: "GET_USER",
 *   GET_USER_FULFILLED: "GET_USER_FULFILLED",
 *   GET_USER_PENDING: "GET_USER_PENDING",
 *   GET_USER_REJECTED: "GET_USER_REJECTED"
 * }
 */

const defaultSuffixes = ['', '_PENDING', '_FULFILLED', '_REJECTED']

const createActionsTypes = (actions, suffixes = defaultSuffixes) => {
  const addSuffixes = action =>
    suffixes.reduce((acc, suffix) => {
      const name = `${action}${suffix}`
      acc[name] = name
      return acc
    }, {})

  const actionTypes = actions.reduce(
    (acc, item) => ({
      ...acc,
      ...addSuffixes(item),
    }),
    {}
  )

  return Object.freeze(actionTypes)
}

export default createActionsTypes([
  // app
  'SET_CONNECTION_STATUS',
  'SET_ALERT_STATUS',
  'CLEAN_ALERT_STATUS',

  // auth
  'LOGIN',
  'FACEBOOK_LOGIN',
  'ALREADY_LOGGED_IN',
  'RESET_PASSWORD',
  'CLEAR_RESET_PASSWORD',
  'REFRESH_TOKEN',
  'REFRESH_TOKEN_BACKGROUND',
  'CURRENT_USER_AUTHENTICATED',
  'USER_REGISTER_DEVICE',

  // user
  'GET_USER',
  'CREATE_USER',
  'CREATE_USER_WITH_FACEBOOK',
  'USER_SEARCH',
  'CURRENT_USER',
  'UPDATE_CURRENT_USER_PROFILE',
  'UPDATE_CURRENT_USER_PROFILE_IMAGE',
  'UPDATE_USER_PREFERENCE',

  // newsfeed
  'GET_UPDATES',
  'GET_MORE_UPDATES',
  'GET_UPDATE',
  'DELETE_UPDATE',
  'EDIT_UPDATE',
  'GET_COMMENTS',
  'GET_PREVIOUS_COMMENTS',
  'GET_MORE_COMMENTS',
  'ADD_COMMENT',
  'REMOVE_COMMENT',
  'UPDATE_COMMENT',
  'REFRESH_UPDATES',
  'TOGGLE_LIKE',

  // trails
  'SET_TRAIL_LIST_TYPE',
  'GET_TRAILS',
  'GET_FAVORITE_TRAILS',
  'GET_TRAIL_DETAILS',
  'GET_TRAIL_PICTURES',
  'GET_TRAIL_REVIEWS',
  'CREATE_REVIEW',
  'DELETE_REVIEW',
  'EDIT_REVIEW',
  'GET_TRAIL_POIS',
  'GET_TRAIL_RIDES',
  'TOGGLE_TRAIL_FAVORITE',
  'SET_BOUND_BOX',
  'RESET_SOURCE',
  'SET_LATITUDE_LONGITUDE',
  'ADD_TRAIL_IMAGE',
  'DELETE_TRAIL_PICTURE',
  'TRAIL_TOGGLE_SELECT_PICTURE',
  'CREATE_TRAIL',
  'EDIT_TRAIL',
  'DELETE_TRAIL',
  'SET_TRAIL_FILTERS',

  // poi
  'GET_POIS',
  'ADD_POI',
  'EDIT_POI',
  'DELETE_POI',

  // friends
  'GET_FRIENDS',
  'GET_FRIENDS_PAGINATION',
  'GET_FRIEND_SEARCH',
  'GET_FRIEND_SEARCH_PAGINATION',
  'GET_FRIENDS_BY_KM',
  'GET_FRIENDS_BY_KM_PAGINATION',
  'CLEAR_FRIEND_SEARCH',
  'GET_PENDING_FRIEND_INVITATIONS',
  'GET_IGNORED_FRIEND_INVITATIONS',
  'PENDING_FRIEND_INVITATIONS_PAGINATION',
  'IGNORED_FRIEND_INVITATIONS_PAGINATION',
  'GET_FRIEND_SUGGESTIONS',
  'ACCEPT_FRIEND_REQUEST',
  'IGNORE_FRIEND_REQUEST',
  'DELETE_FRIEND_REQUEST',
  'REMOVE_FRIEND_REQUEST_FROM_LIST',
  'ADD_SUGGESTED_OUTBOUND_REQUEST_ID',
  'ADD_FRIEND',
  'REMOVE_FRIEND',
  'REMOVE_FRIEND_FROM_LIST',

  // horses
  'GET_HORSES',
  'GET_MORE_HORSES',
  'GET_HORSES_JOURNAL',
  'SAVE_HORSE_JOURNAL',
  'EDIT_HORSE_JOURNAL',
  'DELETE_HORSE_JOURNAL',
  'EDIT_SHARESCOPE',
  'ADD_HORSE',
  'EDIT_HORSE',
  'ADD_HORSE_CLEAR',
  'ADD_HORSE_IMAGE',
  'DELETE_HORSE_IMAGE',
  'SET_PREVIOUS_STEP',
  'SET_NEXT_STEP',
  'EDIT_HORSE_USER',
  'ADD_FRIEND_TEAM',
  'GET_HORSE_USER',
  'GET_HORSE_ALBUM',
  'GET_HORSE_PROFILE',
  'SET_HORSE_PROFILE_IMAGE',
  'HORSE_TOGGLE_SELECT_IMAGE',
  'HORSE_CLEAR_SELECTED_IMAGES',
  'SET_HORSE',
  'SELECT_RIDE',
  'UNSELECT_RIDE',
  'SET_LAST_ACCESSED_HORSE',
  'HORSE_CLEAR_SELECTED_RIDES',
  'UPDATE_VERIFICATION_STATE',
  'GET_ENTRY',
  'ADD_POST_IMAGE',

  // record
  'SET_CURRENT_LOCATION',
  'SET_CURRENT_REGION',
  'SET_FOCUS_USER_LOCATION',
  'START_RECORDING',
  'ADD_RECORD_LOCATION',
  'STOP_RECORDING',
  'PAUSE_RECORDING',
  'RESUME_RECORDING',
  'SET_RECORDING_HORSE',
  'SAVE_RECORDING',
  'CLEAR_RECORDING',
  'RECORDING_FOLLOW_TRAIL',
  'RECORDING_SHOULD_FOLLOW_TRAIL',
  'STOP_FOLLOWING_TRAIL',

  // notifications
  'GET_NOTIFICATIONS',
  'GET_NOTIFICATION',
  'GET_NOTIFICATIONS_PAGINATION',
  'GET_UNREAD_NOTIFICATION_COUNT',
  'UPDATE_READ_MARKER',
  'ADD_NOTIFICATION',
  'REMOVE_NOTIFICATION',
  'MERGE_NEW_NOTIFICATIONS',
  'MARK_NOTIFICATIONS_READ',

  // globals
  'GALLERY_ADD_IMAGES',
  'GALLERY_CLEAR_IMAGES',

  // settings
  'CHANGE_LANGUAGE',
  'TOGGLE_STATUS_BAR',
  'SETTINGS_ENABLE_PUSH_NOTIFICATIONS',
  // rides
  'GET_RIDES',
  'GET_RIDE_DETAILS',
  'GET_TRAILS_PASSED',
])
