import React, { PureComponent } from 'react'
import { StyleSheet, Text } from 'react-native'

const Icons = {
  add_photo_for_album: '\ue900',
  add_photo: '\ue901',
  add_to_journal: '\ue902',
  add_video: '\ue903',
  add_video_youtube: '\ue904',
  add: '\ue905',
  archived_horses: '\ue906',
  arrow_ascent: '\ue907',
  arrow_descent: '\ue908',
  arrow_left: '\ue909',
  arrow_right: '\ue90a',
  calendar_today: '\ue90b',
  calendar: '\ue90c',
  comment: '\ue90d',
  delete: '\ue90e',
  driving: '\ue90f',
  edit: '\ue910',
  elevation: '\ue911',
  error_message: '\ue912',
  facebook: '\ue913',
  filter_off: '\ue914',
  filter_on: '\ue915',
  filter: '\ue916',
  flag_report: '\ue917',
  follow_trail: '\ue918',
  form_send: '\ue919',
  friends: '\ue91a',
  fullscreen: '\ue91b',
  gallery: '\ue91c',
  getting_started: '\ue91d',
  heart: '\ue91e',
  help: '\ue91f',
  journal: '\ue920',
  horse_team: '\ue921',
  horse: '\ue922',
  info: '\ue923',
  km_marker: '\ue924',
  link_normal: '\ue925',
  list: '\ue926',
  list_2: '\ue927',
  lock_closed: '\ue928',
  lock_opened: '\ue929',
  log_out: '\ue92a',
  map_controls_km_without_bg: '\ue92b',
  map_controls_km: '\ue92c',
  map_controls_layers: '\ue92d',
  map_controls_poi_without_bg: '\ue92e',
  map_controls_poi: '\ue92f',
  map_2: '\ue930',
  map: '\ue931',
  my_location: '\ue932',
  navigation_drawer: '\ue933',
  newsfeed: '\ue934',
  notification: '\ue935',
  poi_for_button_without_bg: '\ue936',
  poi_for_button: '\ue937',
  poi_camping_without_bg: '\ue938',
  poi_camping: '\ue939',
  poi_eatery_without_bg: '\ue93a',
  poi_eatery: '\ue93b',
  poi_equestrian_facility_without_bg: '\ue93c',
  poi_equestrian_facility: '\ue93d',
  poi_lodging_without_bg: '\ue93e',
  poi_lodging: '\ue93f',
  poi_no_category_defined_without_bg: '\ue940',
  poi_no_category_defined: '\ue941',
  poi_parking_without_bg: '\ue942',
  poi_parking: '\ue943',
  poi_picnic_place_without_bg: '\ue944',
  poi_picnic_place: '\ue945',
  poi_tap_water_without_bg: '\ue946',
  poi_tap_water: '\ue947',
  poi_viewpoint_without_bg: '\ue948',
  poi_viewpoint: '\ue949',
  poi_visitor_center_without_bg: '\ue94a',
  poi_visitor_center: '\ue94b',
  poi_warning_without_bg: '\ue94c',
  poi_warning: '\ue94d',
  poi_water_crossing_without_bg: '\ue94e',
  poi_water_crossing: '\ue94f',
  premium: '\ue950',
  profile: '\ue951',
  record_ride: '\ue952',
  reduce_screen: '\ue953',
  results_winner_badge: '\ue954',
  results_winner_cup: '\ue955',
  resume: '\ue956',
  reviews: '\ue957',
  ride_current_location: '\ue958',
  ride_end_point: '\ue959',
  rides_option_B: '\ue95a',
  rides: '\ue95b',
  search: '\ue95c',
  send_feedback_option_a: '\ue95d',
  send_feedback_option_b: '\ue95e',
  settings_about: '\ue95f',
  settings_account: '\ue960',
  settings_horse_height: '\ue961',
  settings_notifications: '\ue962',
  settings_rate_app: '\ue963',
  settings_tick: '\ue964',
  settings_units_of_measure: '\ue965',
  settings: '\ue966',
  sharescope_horseteam: '\ue967',
  sharescope_private: '\ue968',
  sharescope_public: '\ue969',
  star_review: '\ue96a',
  stats_duration: '\ue96b',
  stats_nr_rides: '\ue96c',
  stats: '\ue96d',
  stop: '\ue96e',
  trail_marker_end: '\ue96f',
  trail_marker_start: '\ue970',
  trail_type_one_way_trip: '\ue971',
  trail_type_round_trip: '\ue972',
  trails: '\ue973',
  version: '\ue974',
  visibility_off: '\ue975',
  visibility_on: '\ue976',
}

const DEFAULT_ICON_COLOR = '#B1B1B1'

class Icon extends PureComponent {
  render() {
    const { name, style, tintColor = DEFAULT_ICON_COLOR, ...props } = this.props

    return (
      <Text style={[styles.icon, { color: tintColor }, style]} {...props}>
        {Icons[name]}
      </Text>
    )
  }
}

const styles = StyleSheet.create({
  icon: {
    fontFamily: 'Horsha',
    fontSize: 24,
  },
})

export default Icon
